image: gitpod/workspace-full-vnc

additionalRepositories:
  - url: https://gitlab.com/gitpod-examples/fe-angular
    checkoutLocation: febe-fe-angular

workspaceLocation: febe-be-spring/fullstack.code.workspace

tasks:
  - name: get MVN ready
    init: mvn clean && mvn install -DsktpTests
    command: |
      gp open src/main/java/com/subinamathew/demo/controller/Controller.java
      java -jar target/*.jar

  - name: frontend
    before: |
      cd ../febe-fe-angular
      npm install -g @angular/cli
      npm install
      npm audit fix
      gp env CHROME_BIN=/usr/bin/google-chrome
      gp env BROWSER="Chrome_without_Sandbox"
      
    command:  |
      { gp await-port 4200 && sleep 5 && gp preview $(gp url 4200) & } & > /dev/null
      npm start

vscode:
  extensions:
    - Angular.ng-template
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - vscjava.vscode-java-pack
