image: gitpod/workspace-full-vnc

additionalRepositories:
  - url: https://gitlab.com/gitpod-examples/fe-angular
    checkoutLocation: febe-fe-angular

workspaceLocation: springboot-helloworld/fullstack.code.workspace

tasks:
  - name: get MVN ready
    init: mvn clean && mvn install -DskipTests
    command: |
      gp open src/main/java/com/subinamathew/demo/controller/Controller.java
      java -jar target/*.jar

  - name: frontend
    before: |
      cd ../febe-fe-angular
      npm install -g @angular/cli
      npm install
      npm audit fix
      gp env CHROME_BIN=/usr/bin/google-chrome
      gp env BROWSER="Chrome_without_Sandbox"
    command:  |
      { gp await-port 4200 && sleep 5 && gp preview $(gp url 4200) & } & > /dev/null
      gp await-port 8080
      BACKEND_URL=$(gp url 8080)
      sed 's,8080-replaceME,'"$BACKEND_URL"',' src/environments/environment.gitpod.template.ts > src/environments/environment.mygitpod.ts
      npm start

ports:
  - port: 8080
    onOpen: ignore
    visibility: public

  - port: 4200
    onOpen: open-browser

  - port: 5900
    onOpen: ignore

  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - Angular.ng-template
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - vscjava.vscode-java-pack
